package pojos;
// Generated Apr 12, 2017 3:51:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbClassrooms generated by hbm2java
 */
public class TbClassrooms  implements java.io.Serializable {


     private Integer classroomsId;
     private String classroomsName;
     private Set tbSchedules = new HashSet(0);

    public TbClassrooms() {
    }

	
    public TbClassrooms(String classroomsName) {
        this.classroomsName = classroomsName;
    }
    public TbClassrooms(String classroomsName, Set tbSchedules) {
       this.classroomsName = classroomsName;
       this.tbSchedules = tbSchedules;
    }
   
    public Integer getClassroomsId() {
        return this.classroomsId;
    }
    
    public void setClassroomsId(Integer classroomsId) {
        this.classroomsId = classroomsId;
    }
    public String getClassroomsName() {
        return this.classroomsName;
    }
    
    public void setClassroomsName(String classroomsName) {
        this.classroomsName = classroomsName;
    }
    public Set getTbSchedules() {
        return this.tbSchedules;
    }
    
    public void setTbSchedules(Set tbSchedules) {
        this.tbSchedules = tbSchedules;
    }




}


