package pojos;
// Generated Apr 12, 2017 3:51:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbLogin generated by hbm2java
 */
public class TbLogin  implements java.io.Serializable {


     private Integer loginId;
     private String loginUser;
     private String loginPass;
     private int loginRole;
     private int loginFirstLogin;
     private Set tbTeacherses = new HashSet(0);
     private Set tbStudentses = new HashSet(0);

    public TbLogin() {
    }

	
    public TbLogin(String loginUser, String loginPass, int loginRole, int loginFirstLogin) {
        this.loginUser = loginUser;
        this.loginPass = loginPass;
        this.loginRole = loginRole;
        this.loginFirstLogin = loginFirstLogin;
    }
    public TbLogin(String loginUser, String loginPass, int loginRole, int loginFirstLogin, Set tbTeacherses, Set tbStudentses) {
       this.loginUser = loginUser;
       this.loginPass = loginPass;
       this.loginRole = loginRole;
       this.loginFirstLogin = loginFirstLogin;
       this.tbTeacherses = tbTeacherses;
       this.tbStudentses = tbStudentses;
    }
   
    public Integer getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }
    public String getLoginUser() {
        return this.loginUser;
    }
    
    public void setLoginUser(String loginUser) {
        this.loginUser = loginUser;
    }
    public String getLoginPass() {
        return this.loginPass;
    }
    
    public void setLoginPass(String loginPass) {
        this.loginPass = loginPass;
    }
    public int getLoginRole() {
        return this.loginRole;
    }
    
    public void setLoginRole(int loginRole) {
        this.loginRole = loginRole;
    }
    public int getLoginFirstLogin() {
        return this.loginFirstLogin;
    }
    
    public void setLoginFirstLogin(int loginFirstLogin) {
        this.loginFirstLogin = loginFirstLogin;
    }
    public Set getTbTeacherses() {
        return this.tbTeacherses;
    }
    
    public void setTbTeacherses(Set tbTeacherses) {
        this.tbTeacherses = tbTeacherses;
    }
    public Set getTbStudentses() {
        return this.tbStudentses;
    }
    
    public void setTbStudentses(Set tbStudentses) {
        this.tbStudentses = tbStudentses;
    }




}


