package pojos;
// Generated Apr 12, 2017 3:51:30 PM by Hibernate Tools 4.3.1



/**
 * TbSchedule generated by hbm2java
 */
public class TbSchedule  implements java.io.Serializable {


     private Integer scheduleId;
     private TbClassrooms tbClassrooms;
     private TbSubjects tbSubjects;
     private String scheduleStartDate;
     private String scheduleEndDate;
     private int scheduleDay;
     private int scheduleStartTime;
     private int scheduleEndTime;

    public TbSchedule() {
    }

    public TbSchedule(TbClassrooms tbClassrooms, TbSubjects tbSubjects, String scheduleStartDate, String scheduleEndDate, int scheduleDay, int scheduleStartTime, int scheduleEndTime) {
       this.tbClassrooms = tbClassrooms;
       this.tbSubjects = tbSubjects;
       this.scheduleStartDate = scheduleStartDate;
       this.scheduleEndDate = scheduleEndDate;
       this.scheduleDay = scheduleDay;
       this.scheduleStartTime = scheduleStartTime;
       this.scheduleEndTime = scheduleEndTime;
    }
   
    public Integer getScheduleId() {
        return this.scheduleId;
    }
    
    public void setScheduleId(Integer scheduleId) {
        this.scheduleId = scheduleId;
    }
    public TbClassrooms getTbClassrooms() {
        return this.tbClassrooms;
    }
    
    public void setTbClassrooms(TbClassrooms tbClassrooms) {
        this.tbClassrooms = tbClassrooms;
    }
    public TbSubjects getTbSubjects() {
        return this.tbSubjects;
    }
    
    public void setTbSubjects(TbSubjects tbSubjects) {
        this.tbSubjects = tbSubjects;
    }
    public String getScheduleStartDate() {
        return this.scheduleStartDate;
    }
    
    public void setScheduleStartDate(String scheduleStartDate) {
        this.scheduleStartDate = scheduleStartDate;
    }
    public String getScheduleEndDate() {
        return this.scheduleEndDate;
    }
    
    public void setScheduleEndDate(String scheduleEndDate) {
        this.scheduleEndDate = scheduleEndDate;
    }
    public int getScheduleDay() {
        return this.scheduleDay;
    }
    
    public void setScheduleDay(int scheduleDay) {
        this.scheduleDay = scheduleDay;
    }
    public int getScheduleStartTime() {
        return this.scheduleStartTime;
    }
    
    public void setScheduleStartTime(int scheduleStartTime) {
        this.scheduleStartTime = scheduleStartTime;
    }
    public int getScheduleEndTime() {
        return this.scheduleEndTime;
    }
    
    public void setScheduleEndTime(int scheduleEndTime) {
        this.scheduleEndTime = scheduleEndTime;
    }




}


