package pojos;
// Generated Apr 12, 2017 3:51:30 PM by Hibernate Tools 4.3.1



/**
 * TbSubjectsStudents generated by hbm2java
 */
public class TbSubjectsStudents  implements java.io.Serializable {


     private Integer subjectsStudentsId;
     private TbStudents tbStudents;
     private TbSubjects tbSubjects;
     private int week1;
     private int week2;
     private int week3;
     private int week4;
     private int week5;
     private int week6;
     private int week7;
     private int week8;
     private int week9;
     private int week10;
     private int week11;
     private int week12;
     private int week13;
     private int week14;
     private int week15;

    public TbSubjectsStudents() {
    }

    public TbSubjectsStudents(TbStudents tbStudents, TbSubjects tbSubjects, int week1, int week2, int week3, int week4, int week5, int week6, int week7, int week8, int week9, int week10, int week11, int week12, int week13, int week14, int week15) {
       this.tbStudents = tbStudents;
       this.tbSubjects = tbSubjects;
       this.week1 = week1;
       this.week2 = week2;
       this.week3 = week3;
       this.week4 = week4;
       this.week5 = week5;
       this.week6 = week6;
       this.week7 = week7;
       this.week8 = week8;
       this.week9 = week9;
       this.week10 = week10;
       this.week11 = week11;
       this.week12 = week12;
       this.week13 = week13;
       this.week14 = week14;
       this.week15 = week15;
    }
   
    public Integer getSubjectsStudentsId() {
        return this.subjectsStudentsId;
    }
    
    public void setSubjectsStudentsId(Integer subjectsStudentsId) {
        this.subjectsStudentsId = subjectsStudentsId;
    }
    public TbStudents getTbStudents() {
        return this.tbStudents;
    }
    
    public void setTbStudents(TbStudents tbStudents) {
        this.tbStudents = tbStudents;
    }
    public TbSubjects getTbSubjects() {
        return this.tbSubjects;
    }
    
    public void setTbSubjects(TbSubjects tbSubjects) {
        this.tbSubjects = tbSubjects;
    }
    public int getWeek1() {
        return this.week1;
    }
    
    public void setWeek1(int week1) {
        this.week1 = week1;
    }
    public int getWeek2() {
        return this.week2;
    }
    
    public void setWeek2(int week2) {
        this.week2 = week2;
    }
    public int getWeek3() {
        return this.week3;
    }
    
    public void setWeek3(int week3) {
        this.week3 = week3;
    }
    public int getWeek4() {
        return this.week4;
    }
    
    public void setWeek4(int week4) {
        this.week4 = week4;
    }
    public int getWeek5() {
        return this.week5;
    }
    
    public void setWeek5(int week5) {
        this.week5 = week5;
    }
    public int getWeek6() {
        return this.week6;
    }
    
    public void setWeek6(int week6) {
        this.week6 = week6;
    }
    public int getWeek7() {
        return this.week7;
    }
    
    public void setWeek7(int week7) {
        this.week7 = week7;
    }
    public int getWeek8() {
        return this.week8;
    }
    
    public void setWeek8(int week8) {
        this.week8 = week8;
    }
    public int getWeek9() {
        return this.week9;
    }
    
    public void setWeek9(int week9) {
        this.week9 = week9;
    }
    public int getWeek10() {
        return this.week10;
    }
    
    public void setWeek10(int week10) {
        this.week10 = week10;
    }
    public int getWeek11() {
        return this.week11;
    }
    
    public void setWeek11(int week11) {
        this.week11 = week11;
    }
    public int getWeek12() {
        return this.week12;
    }
    
    public void setWeek12(int week12) {
        this.week12 = week12;
    }
    public int getWeek13() {
        return this.week13;
    }
    
    public void setWeek13(int week13) {
        this.week13 = week13;
    }
    public int getWeek14() {
        return this.week14;
    }
    
    public void setWeek14(int week14) {
        this.week14 = week14;
    }
    public int getWeek15() {
        return this.week15;
    }
    
    public void setWeek15(int week15) {
        this.week15 = week15;
    }




}


