package pojos;
// Generated Apr 12, 2017 3:51:30 PM by Hibernate Tools 4.3.1



/**
 * TbTeachers generated by hbm2java
 */
public class TbTeachers  implements java.io.Serializable {


     private String teachersId;
     private TbLogin tbLogin;
     private String teachersName;

    public TbTeachers() {
    }

    public TbTeachers(String teachersId, TbLogin tbLogin, String teachersName) {
       this.teachersId = teachersId;
       this.tbLogin = tbLogin;
       this.teachersName = teachersName;
    }
   
    public String getTeachersId() {
        return this.teachersId;
    }
    
    public void setTeachersId(String teachersId) {
        this.teachersId = teachersId;
    }
    public TbLogin getTbLogin() {
        return this.tbLogin;
    }
    
    public void setTbLogin(TbLogin tbLogin) {
        this.tbLogin = tbLogin;
    }
    public String getTeachersName() {
        return this.teachersName;
    }
    
    public void setTeachersName(String teachersName) {
        this.teachersName = teachersName;
    }




}


