package pojos;
// Generated Jun 5, 2017 12:08:07 PM by Hibernate Tools 4.3.1



/**
 * TbLogin generated by hbm2java
 */
public class TbLogin  implements java.io.Serializable {


     private Integer loginId;
     private String loginUser;
     private String loginPassword;
     private int loginRole;

    public TbLogin() {
    }

    public TbLogin(String loginUser, String loginPassword, int loginRole) {
       this.loginUser = loginUser;
       this.loginPassword = loginPassword;
       this.loginRole = loginRole;
    }
   
    public Integer getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }
    public String getLoginUser() {
        return this.loginUser;
    }
    
    public void setLoginUser(String loginUser) {
        this.loginUser = loginUser;
    }
    public String getLoginPassword() {
        return this.loginPassword;
    }
    
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }
    public int getLoginRole() {
        return this.loginRole;
    }
    
    public void setLoginRole(int loginRole) {
        this.loginRole = loginRole;
    }




}


