package pojos;
// Generated Jun 5, 2017 12:08:07 PM by Hibernate Tools 4.3.1



/**
 * TbUser generated by hbm2java
 */
public class TbUser  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private String userPhone;
     private String userIdentifyCard;
     private String userAddress;

    public TbUser() {
    }

    public TbUser(String userName, String userPhone, String userIdentifyCard, String userAddress) {
       this.userName = userName;
       this.userPhone = userPhone;
       this.userIdentifyCard = userIdentifyCard;
       this.userAddress = userAddress;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }
    public String getUserIdentifyCard() {
        return this.userIdentifyCard;
    }
    
    public void setUserIdentifyCard(String userIdentifyCard) {
        this.userIdentifyCard = userIdentifyCard;
    }
    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }




}


