/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import general.ChessBoard;
import general.ChessSide;
import general.GameMode;
import javax.swing.JButton;
import javax.swing.JFrame;
/**
 *
 * @author VuQuang
 */
public class ChessGui extends javax.swing.JFrame {

    /**
     * Creates new form ChessGui
     */
    public ChessGui() {
        initComponents();
        setTitle("Chess Game");
        setSize(800,700);
        setResizable(false);
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        //addChessBoard(GameMode.VsHuman);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogClient = new javax.swing.JFrame();
        jButtonClientCancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldClientIP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldClientPort = new javax.swing.JTextField();
        jButtonClientOK = new javax.swing.JButton();
        jDialogServer = new javax.swing.JFrame();
        jButtonServerCancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldServerIP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldServerPort = new javax.swing.JTextField();
        jButtonServerOK = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuNewGame = new javax.swing.JMenu();
        jMenuItemVsComputer = new javax.swing.JMenuItem();
        jMenuItemVsHuman = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemNetworkClient = new javax.swing.JMenuItem();
        jMenuItemNetworkServer = new javax.swing.JMenuItem();

        jButtonClientCancel.setText("Cancel");
        jButtonClientCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientCancelActionPerformed(evt);
            }
        });

        jLabel5.setText("IP");

        jTextFieldClientIP.setText("127.0.0.1");

        jLabel6.setText("Port");

        jTextFieldClientPort.setText("9090");

        jButtonClientOK.setText("OK");
        jButtonClientOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogClientLayout = new javax.swing.GroupLayout(jDialogClient.getContentPane());
        jDialogClient.getContentPane().setLayout(jDialogClientLayout);
        jDialogClientLayout.setHorizontalGroup(
            jDialogClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogClientLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jDialogClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jDialogClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDialogClientLayout.createSequentialGroup()
                        .addComponent(jButtonClientOK, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jButtonClientCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldClientIP)
                    .addComponent(jTextFieldClientPort))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jDialogClientLayout.setVerticalGroup(
            jDialogClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogClientLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jDialogClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldClientIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldClientPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jDialogClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClientOK)
                    .addComponent(jButtonClientCancel))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jButtonServerCancel.setText("Cancel");
        jButtonServerCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonServerCancelActionPerformed(evt);
            }
        });

        jLabel7.setText("IP");

        jTextFieldServerIP.setText("127.0.0.1");

        jLabel8.setText("Port");

        jTextFieldServerPort.setText("9090");

        jButtonServerOK.setText("OK");
        jButtonServerOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonServerOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogServerLayout = new javax.swing.GroupLayout(jDialogServer.getContentPane());
        jDialogServer.getContentPane().setLayout(jDialogServerLayout);
        jDialogServerLayout.setHorizontalGroup(
            jDialogServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogServerLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jDialogServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jDialogServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDialogServerLayout.createSequentialGroup()
                        .addComponent(jButtonServerOK, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jButtonServerCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldServerIP)
                    .addComponent(jTextFieldServerPort))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jDialogServerLayout.setVerticalGroup(
            jDialogServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogServerLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jDialogServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldServerIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jDialogServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonServerOK)
                    .addComponent(jButtonServerCancel))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuNewGame.setText("New Game");

        jMenuItemVsComputer.setText("vsComputer");
        jMenuItemVsComputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVsComputerActionPerformed(evt);
            }
        });
        jMenuNewGame.add(jMenuItemVsComputer);

        jMenuItemVsHuman.setText("vsHuman");
        jMenuItemVsHuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVsHumanActionPerformed(evt);
            }
        });
        jMenuNewGame.add(jMenuItemVsHuman);

        jMenu1.setText("NetworkHuman");

        jMenuItemNetworkClient.setText("Client");
        jMenuItemNetworkClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNetworkClientActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemNetworkClient);

        jMenuItemNetworkServer.setText("Server");
        jMenuItemNetworkServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNetworkServerActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemNetworkServer);

        jMenuNewGame.add(jMenu1);

        jMenuBar.add(jMenuNewGame);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemVsHumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVsHumanActionPerformed
        // TODO add your handling code here:
        addChessBoard(GameMode.VsHuman);
    }//GEN-LAST:event_jMenuItemVsHumanActionPerformed

    private void jMenuItemVsComputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVsComputerActionPerformed
        // TODO add your handling code here:
        addChessBoard(GameMode.VsComputer);
    }//GEN-LAST:event_jMenuItemVsComputerActionPerformed

    private void jMenuItemNetworkClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNetworkClientActionPerformed
        // TODO add your handling code here:
        jDialogClient.setSize(500, 400);
        jDialogClient.setVisible(true);
    }//GEN-LAST:event_jMenuItemNetworkClientActionPerformed

    private void jMenuItemNetworkServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNetworkServerActionPerformed
        // TODO add your handling code here:
        jDialogServer.setSize(500, 400);
        jDialogServer.setVisible(true);
    }//GEN-LAST:event_jMenuItemNetworkServerActionPerformed

    private void jButtonClientCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientCancelActionPerformed
        // TODO add your handling code here:
        jDialogClient.setVisible(false);
        
    }//GEN-LAST:event_jButtonClientCancelActionPerformed

    private void jButtonClientOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientOKActionPerformed
        // TODO add your handling code here:
        String Ip = jTextFieldClientIP.getText();
        String Port = jTextFieldClientPort.getText();
        jDialogClient.setVisible(false);
        start_As_Client(Ip, Port);
    }//GEN-LAST:event_jButtonClientOKActionPerformed

    private void jButtonServerCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonServerCancelActionPerformed
        // TODO add your handling code here:
        jDialogServer.setVisible(false);
    }//GEN-LAST:event_jButtonServerCancelActionPerformed

    private void jButtonServerOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonServerOKActionPerformed
        // TODO add your handling code here:
        String Ip = jTextFieldServerIP.getText();
        String Port = jTextFieldServerPort.getText();
        jDialogServer.setVisible(false);
        start_As_Server(Ip, Port);
        
    }//GEN-LAST:event_jButtonServerOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChessGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChessGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChessGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChessGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChessGui().setVisible(true);
            }
        });
    }
    
    private void addChessBoard(GameMode mode) {
        ChessBoard board = new ChessBoard(ChessSide.White, mode, 75);
        this.setContentPane(board);
        this.revalidate();
    }
    
    public void start_As_Server(String Ip,String Port) {
        ChessBoard board = new ChessBoard(ChessSide.White, GameMode.VsNetWorkHuman, 75);
        this.setContentPane(board);
        board.start_As_Server(Ip, Port);
        setTitle("Server player");
        
    }
    public void start_As_Client(String Ip,String Port) {
        ChessBoard board = new ChessBoard(ChessSide.White, GameMode.VsNetWorkHuman, 75);
        this.setContentPane(board);
        board.start_As_Client(Ip, Port);
        setTitle("Client player");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClientCancel;
    private javax.swing.JButton jButtonClientOK;
    private javax.swing.JButton jButtonServerCancel;
    private javax.swing.JButton jButtonServerOK;
    private javax.swing.JFrame jDialogClient;
    private javax.swing.JFrame jDialogServer;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemNetworkClient;
    private javax.swing.JMenuItem jMenuItemNetworkServer;
    private javax.swing.JMenuItem jMenuItemVsComputer;
    private javax.swing.JMenuItem jMenuItemVsHuman;
    private javax.swing.JMenu jMenuNewGame;
    private javax.swing.JTextField jTextFieldClientIP;
    private javax.swing.JTextField jTextFieldClientPort;
    private javax.swing.JTextField jTextFieldServerIP;
    private javax.swing.JTextField jTextFieldServerPort;
    // End of variables declaration//GEN-END:variables
}
