
import dao.SubjectsStudentsDao;
import javax.swing.JOptionPane;
import dao.*;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import pojos.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pham Tien
 */
public class JFrameStudent_Attendance extends javax.swing.JFrame {

    /**
     * Creates new form JFrameStudent_Attendance
     */
    public JFrameStudent_Attendance() {
        initComponents();
        loadDataCombo();
    }

    public void loadDataCombo() {
        StudentSelected stu = new StudentSelected();
        TbSubjects sub = new TbSubjects();

        for (TbSubjectsStudents ss : SubjectsStudentsDao.listSubStu()) {
            String idStu = ss.getTbStudents().getStudentsId();
            if (idStu.equals(stu.getStudentsId())) {
                String subName = SubjectsDao.getNameById(ss.getTbSubjects().getSubjectsId());
//                System.out.println(subName);
                jComboSubjects.addItem(subName);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboSubjects = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 120));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton4.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        jButton4.setText("Đăng xuất");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Documents\\K2014 nam 3\\Hoc Ki 2\\Java\\Tuan 4\\Attendance\\pic\\stu_avatar.png")); // NOI18N
        jLabel2.setText("Xin chào Học Sinh");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Điểm Danh");

        jComboSubjects.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Chọn Môn:");

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Điểm Danh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("D:\\Documents\\K2014 nam 3\\Hoc Ki 2\\Java\\Tuan 4\\Attendance\\pic\\stu_menu_create_back.png")); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("  Quay Lại");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(138, 138, 138)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton4)
                        .addComponent(jLabel4)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Bạn có thật sự muốn đăng xuất?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            JFrameLogin jf = new JFrameLogin();
            jf.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        StudentSelected stu = new StudentSelected();
        TbSubjects sub = new TbSubjects();
        int isSuccess = 0;
        int iWeek = 0;
        long curTime = 0;
        int sizeComboSub = jComboSubjects.getItemCount();
        if (sizeComboSub == 0) {
            JOptionPane.showMessageDialog(rootPane, "Sinh viên này chưa có môn học để điểm danh!");
        } else {
            for (TbSubjectsStudents ss : SubjectsStudentsDao.listSubStu()) {
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                SimpleDateFormat formatter2 = new SimpleDateFormat("H");
                String idStu = ss.getTbStudents().getStudentsId();
                if (idStu.equals(stu.getStudentsId())) {
                    String idSub = ss.getTbSubjects().getSubjectsId();
                    String curDate = new SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().getTime());
                    String curHour = new SimpleDateFormat("H").format(Calendar.getInstance().getTime());
                    DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
                    Date curDatee;
                    int thisHour = Integer.parseInt(curHour) * 60 * 60 * 1000;
                    
                    long curHourr = 0;
                    try {
                        
                        curDatee = df.parse(curDate);
                        curTime = curDatee.getTime() / 1000;
                    } catch (ParseException ex) {
                        Logger.getLogger(JFrameStudent_Attendance.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    String startDate = "";
                    int startHour = 0;
                    int endHour = 0;
                    for (TbSchedule sche : ScheduleDao.listSche()) {
                        String idSubOfSche = sche.getTbSubjects().getSubjectsId();
                        if (idSub.equals(idSubOfSche)) {
                            startDate = sche.getScheduleStartDate();
                            startHour = sche.getScheduleStartTime();
                            endHour = sche.getScheduleEndTime();
                        }
                    }
                    for (int i = 0; i < 15; i++) {
                        Date attendanceD;
                        attendanceD = new Date();
                        try {
                            attendanceD = formatter.parse(startDate);
                        } catch (ParseException ex) {
                            Logger.getLogger(JFrameStudent_Attendance.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        
                        long start = attendanceD.getTime() / 1000;
                        start = (24 * 60 * 60 * 7 * i) + start;
//                        System.out.println(start + ": " + curTime);
                        Date d = new Date(start);
                        String attendanceDate = formatter.format(d); //Ngay de diem danh

                        if (start == curTime) {
                            System.out.println(thisHour);
                            System.out.println(endHour);
                            System.out.println(startHour);
                            if (thisHour <= endHour && thisHour >= startHour) {
                                if (i == 0) {
                                    if (ss.getWeek1() == 0) {
                                        isSuccess = 1;
                                        ss.setWeek1(1);
                                        SubjectsStudentsDao.update(ss);
                                    } else {
                                        isSuccess = 2;
                                    }
                                } else if (i == 1) {
                                    if (ss.getWeek2() == 0) {
                                        isSuccess = 1;
                                        ss.setWeek2(1);
                                        SubjectsStudentsDao.update(ss);
                                    } else {
                                        isSuccess = 2;
                                    }
                                } else if (i == 2) {
                                    if (ss.getWeek3() == 0) {
                                        isSuccess = 1;
                                        ss.setWeek3(1);
                                        SubjectsStudentsDao.update(ss);
                                    } else {
                                        isSuccess = 2;
                                    }
                                } else if (i == 3) {
                                    if (ss.getWeek4() == 0) {
                                        isSuccess = 1;
                                        ss.setWeek4(1);
                                        SubjectsStudentsDao.update(ss);
                                    } else {
                                        isSuccess = 2;
                                    }
                                } else if (i == 4) {
                                    if (ss.getWeek5() == 0) {
                                        isSuccess = 1;
                                        ss.setWeek5(1);
                                        SubjectsStudentsDao.update(ss);
                                    } else {
                                        isSuccess = 2;
                                    }
                                } else if (i == 5) {
                                    if (ss.getWeek6() == 0) {
                                        isSuccess = 1;
                                        ss.setWeek6(1);
                                        SubjectsStudentsDao.update(ss);
                                    } else {
                                        isSuccess = 2;
                                    }
                                } else if (i == 6) {
                                    if (ss.getWeek7() == 0) {
                                        isSuccess = 1;
                                        ss.setWeek7(1);
                                        SubjectsStudentsDao.update(ss);
                                    } else {
                                        isSuccess = 2;
                                    }
                                } else if (i == 7) {
                                    if (ss.getWeek8() == 0) {
                                        isSuccess = 1;
                                        ss.setWeek8(1);
                                        SubjectsStudentsDao.update(ss);
                                    } else {
                                        isSuccess = 2;
                                    }
                                } else if (i == 8) {
                                    if (ss.getWeek9() == 0) {
                                        isSuccess = 1;
                                        ss.setWeek9(1);
                                        SubjectsStudentsDao.update(ss);
                                    } else {
                                        isSuccess = 2;
                                    }
                                } else if (i == 9) {
                                    if (ss.getWeek10() == 0) {
                                        isSuccess = 1;
                                        ss.setWeek10(1);
                                        SubjectsStudentsDao.update(ss);
                                    } else {
                                        isSuccess = 2;
                                    }
                                } else if (i == 10) {
                                    if (ss.getWeek11() == 0) {
                                        isSuccess = 1;
                                        ss.setWeek11(1);
                                        SubjectsStudentsDao.update(ss);
                                    } else {
                                        isSuccess = 2;
                                    }
                                } else if (i == 11) {
                                    if (ss.getWeek12() == 0) {
                                        isSuccess = 1;
                                        ss.setWeek12(1);
                                        SubjectsStudentsDao.update(ss);
                                    } else {
                                        isSuccess = 2;
                                    }
                                } else if (i == 12) {
                                    if (ss.getWeek13() == 0) {
                                        isSuccess = 1;
                                        ss.setWeek13(1);
                                        SubjectsStudentsDao.update(ss);
                                    } else {
                                        isSuccess = 2;
                                    }
                                } else if (i == 13) {
                                    if (ss.getWeek14() == 0) {
                                        isSuccess = 1;
                                        ss.setWeek14(1);
                                        SubjectsStudentsDao.update(ss);
                                    } else {
                                        isSuccess = 2;
                                    }
                                } else if (i == 14) {
                                    if (ss.getWeek15() == 0) {
                                        isSuccess = 1;
                                        ss.setWeek15(1);
                                        SubjectsStudentsDao.update(ss);
                                    } else {
                                        isSuccess = 2;
                                    }
                                }
                            }
                        }
                    }
                    //kiểm tra điểm danh
                    if (isSuccess == 1) {
                        JOptionPane.showMessageDialog(rootPane, "Điểm danh thành công!");
                    } else if (isSuccess == 2) {
                        JOptionPane.showMessageDialog(rootPane, "Bạn đã điểm danh rồi, không thể điểm danh lại!");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Chưa đến lúc điểm danh, vui lòng quay lại sau!");
                    }
                }
            }

        }

//        sub = SubjectsStudentsDao.getTbSubByIdStu(StudentsDao.getStudentsInfo(stu.getStudentsId()));
//        System.out.println(sub.getSubjectsName());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        JFrameStudent jf = new JFrameStudent();
        jf.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameStudent_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameStudent_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameStudent_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameStudent_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameStudent_Attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboSubjects;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
